dist: xenial
language: python
install:
  - pip install tox-travis
script:
  - tox
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
matrix:
  include:
    - python: 3.7
      env: TOXENV=docs
    - python: 3.7
      env: TOXENV=lint
    - python: 3.7
      env: TOXENV=formatting
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
