build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
install:
  - git config --system http.sslcainfo /bin/curl-ca-bundle.crt
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy mingw-w64-x86_64-ca-certificates ca-certificates"
test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/pip.exe install tox"
  - "%PYTHON%/Scripts/tox.exe -e py27"
