build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/pip.exe install tox"
  - "%PYTHON%/Scripts/tox.exe -e py27"
